### PR TITLE
Port to meshery adapter lib and meshkit

### PR DESCRIPTION
**Pull request by utkarsh-pro**
**Description**
This PR ports nginx-adapter to use meshery-adapter-library and meshkit. 

**Notes for Reviewers**
1. Installing through nginx-meshctl deploy is causing the following error:
```
Created namespace "nginx-mesh".
Created SpiffeID CRD.
Waiting for SPIRE to be running...Failed to deploy: unable to deploy SPIRE: SPIRE not ready after 3 minutes
Cleaning up NGINX Service Mesh resources...
All NGINX Service Mesh resources have been deleted.
```

2. Uninstall process is a two step process. Current PR has only first step implemented as the second step will require the help of meshsync.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Build is failing

**Comment by utkarsh-pro** [comment]
For some reason the golangci-lint check is failing although it is showing no errors.
error

**Comment by leecalcote** [comment]
@kushthedude does the golangci-lint configuration look correct to you in this repo?

**Comment by leecalcote** [comment]
Ready for a new release?

**Comment by utkarsh-pro** [comment]
> Ready for a new release?

@leecalcote, this PR was created about a month ago but now `downloadBinary` function is failing because nginx has changed the URL. Also, I think we'd be avoiding automating `nginxctl` download right? I think Abishek will be replacing the auto download function with manual binary placement in PR #19.

**Pull request merged**
